name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.101'
    - name: Install dependencies (.NET)
      run: dotnet restore
    - name: Build (.NET)
      run: dotnet build --configuration Release --no-restore
    - name: Install dependencies (Angular)
      run: npm install
      working-directory: RubberWeb/ClientApp
    - name: Build (Angular)
      run: npm run build -- --prod
      working-directory: RubberWeb/ClientApp
      
